/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/claw-machine.glb --typescript --transform 
Files: public/models/claw-machine.glb [302.43KB] > D:\Projects\my-portfolio\claw-machine-transformed.glb [29.5KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/claw-machine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.003, 0, -1.186]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh geometry={nodes.SM_Body_InnerGlass.geometry} material={materials.PaletteMaterial003} position={[0.003, 0, -1.186]} />
      <mesh geometry={nodes.SM_Hand_2.geometry} material={materials.PaletteMaterial004} position={[0.003, 12.245, -0.775]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.SM_Rope.geometry} material={nodes.SM_Rope.material} position={[0.003, 13.201, -1.186]} rotation={[0, 1.571, 0]} scale={[0.037, 2.064, 0.037]} />
      <mesh geometry={nodes.SM_Joystick.geometry} material={materials.PaletteMaterial005} position={[-1.805, 5.335, 5.179]} rotation={[Math.PI / 5, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/claw-machine-transformed.glb')
