/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gumball-machine.glb --typescript --transform 
Files: public/models/gumball-machine.glb [481.16KB] > D:\Projects\my-portfolio\gumball-machine-transformed.glb [63.15KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gumball-machine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.015, 1.285, -0.009]} scale={0.025}>
        <mesh geometry={nodes.ID3.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.ID3_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-0.503, 0, 0.571]} scale={0.025}>
        <mesh geometry={nodes.ID33.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.ID33_1.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.SketchUp004.geometry} material={materials.PaletteMaterial004} position={[-0.503, 0, 0.571]} scale={0.025} />
      <mesh geometry={nodes.SketchUp005.geometry} material={materials.PaletteMaterial005} position={[-0.503, 0, 0.571]} scale={0.025} />
      <mesh geometry={nodes.SketchUp012.geometry} material={materials.PaletteMaterial001} position={[-0.503, 0, 0.571]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/gumball-machine-transformed.glb')
