/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/claw-machine.glb --typescript --transform 
Files: public/models/claw-machine.glb [301.48KB] > D:\Projects\my-portfolio\claw-machine-transformed.glb [29.18KB] (90%)
*/
'use client';
import React from 'react'
import { useGLTF } from '@react-three/drei'
useGLTF.preload('/models/claw-machine-transformed.glb');

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/claw-machine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SM_Body_InnerGlass.geometry} material={materials.PaletteMaterial003} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.SM_Hand_2.geometry} material={materials.PaletteMaterial004} position={[-0.412, 0, 12.245]} />
      <mesh geometry={nodes.SM_Rope.geometry} material={nodes.SM_Rope.material} position={[0, 0, 13.201]} scale={[0.037, 0.037, 2.064]} />
      <mesh geometry={nodes.SM_Joystick.geometry} material={materials.PaletteMaterial005} position={[-6.365, 1.808, 5.335]} rotation={[0, -Math.PI / 5, -Math.PI / 2]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Cube014_1.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/claw-machine-transformed.glb')
